import { Geist, Geist_Mono } from "next/font/google";
import "../styles/main.scss";
import { GoogleAnalytics } from "@next/third-parties/google";
import ProviderLayout from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LTH Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org/",
              "@type": "WebSite",
              name: "LTH Store",
              url: "https://next-ecommerce-eight-omega.vercel.app",
              potentialAction: {
                "@type": "SearchAction",
                target:
                  "https://next-ecommerce-eight-omega.vercel.app/shop{search_term_string}",
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderLayout>{children}</ProviderLayout>
      </body>
      <GoogleAnalytics gaId="G-1HYQ8XTKYE" />
    </html>
  );
}
