import { Geist, Geist_Mono } from "next/font/google";
import "../styles/main.scss";
import { GoogleAnalytics } from "@next/third-parties/google";
import ProviderLayout from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LTH Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org/",
              "@type": "WebSite",
              name: "LTH Store",
              url: "https://next-ecommerce-eight-omega.vercel.app",
              potentialAction: {
                "@type": "SearchAction",
                target:
                  "https://next-ecommerce-eight-omega.vercel.app/shop{search_term_string}",
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />

        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.__lc = window.__lc || {};
              window.__lc.license = 18939557;
              window.__lc.integration_name = "manual_onboarding";
              window.__lc.product_name = "livechat";
              (function (n, t, c) {
                function i(n) {
                  return e._h ? e._h.apply(null, n) : e._q.push(n);
                }
                var e = {
                  _q: [],
                  _h: null,
                  _v: "2.0",
                  on: function () {
                    i(["on", c.call(arguments)]);
                  },
                  once: function () {
                    i(["once", c.call(arguments)]);
                  },
                  off: function () {
                    i(["off", c.call(arguments)]);
                  },
                  get: function () {
                    if (!e._h)
                      throw new Error(
                        "[LiveChatWidget] You can't use getters before load."
                      );
                    return i(["get", c.call(arguments)]);
                  },
                  call: function () {
                    i(["call", c.call(arguments)]);
                  },
                  init: function () {
                    var n = t.createElement("script");
                    (n.async = !0),
                      (n.type = "text/javascript"),
                      (n.src = "https://cdn.livechatinc.com/tracking.js"),
                      t.head.appendChild(n);
                  },
                };
                !n.__lc.asyncInit && e.init(),
                  (n.LiveChatWidget = n.LiveChatWidget || e);
              })(window, document, [].slice);
            `,
          }}
        />
        <noscript>
          <a href="https://www.livechat.com/chat-with/18939557/" rel="nofollow">
            Chat with us
          </a>
          , powered by
          <a
            href="https://www.livechat.com/?welcome"
            rel="noopener nofollow"
            target="_blank"
          >
            LiveChat
          </a>
        </noscript>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-1HYQ8XTKYE"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag() {
                dataLayer.push(arguments);
              }
              gtag("js", new Date());
              gtag("config", "G-1HYQ8XTKYE");
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderLayout>{children}</ProviderLayout>
      </body>
      <GoogleAnalytics gaId="G-1HYQ8XTKYE" />
    </html>
  );
}
